INSERT INTO USUARIO(USUARIO, PASSWORD, EMAIL, FECHA_NACIMIENTO, NOMBRE, APELLIDO, EDAD, ROL) VALUES
    ('test','$2a$10$bhoNyi0sxaGQu.50zOiUL.SKpSPGHytwGruHhYYP2hSDZpkYHEIri', 'test@test.com', '2012-09-17', 'test','test', 21, 1),
    ('admin','$2a$10$bhoNyi0sxaGQu.50zOiUL.SKpSPGHytwGruHhYYP2hSDZpkYHEIri', 'admin@admin.com', '2012-09-17', 'admin','admin', 99, 0),
    ('user1', '$2a$10$bhoNyi0sxaGQu.50zOiUL.SKpSPGHytwGruHhYYP2hSDZpkYHEIri', 'user1@test.com', '1990-01-15', 'User', 'One', 34, 1),
    ('user2', '$2a$10$bhoNyi0sxaGQu.50zOiUL.SKpSPGHytwGruHhYYP2hSDZpkYHEIri', 'user2@test.com', '1985-05-21', 'User', 'Two', 39, 1),
    ('user3', '$2a$10$bhoNyi0sxaGQu.50zOiUL.SKpSPGHytwGruHhYYP2hSDZpkYHEIri', 'user3@test.com', '2000-12-01', 'User', 'Three', 23, 1),
    ('admin2', '$2a$10$bhoNyi0sxaGQu.50zOiUL.SKpSPGHytwGruHhYYP2hSDZpkYHEIri', 'admin2@admin.com', '1975-07-30', 'Admin', 'Second', 49, 0);


INSERT INTO PRODUCTO(NOMBRE, DESCRIPCION, IMAGEN, PRECIO, STATUS) VALUES
    ('Adidas JumpCrazy', 'Modo rana all day', 'jumpcrazy.jpg', 99.99, 1),
    ( 'Vans Classics', 'Un clasicon', 'vansclassic.jpg', 99.99, 1),
    ( 'DC Big Skater', 'Para ese fan que le encanta quemar zapas caras con la lija del board', 'dcbigskater.jpg', 299.99, 1),
    ( 'Nike Air Max', 'Comodidad y estilo para todos', 'airmax.jpg', 149.99, 1),
    ( 'Converse All Star', 'El clásico de siempre, nunca pasa de moda', 'allstar.jpg', 79.99, 1),
    ( 'Reebok Classic', 'El modelo retro que sigue vigente', 'reebokclassic.jpg', 89.99, 1),
    ( 'Puma Suede', 'Elegancia y rendimiento en uno', 'pumasuede.jpg', 129.99, 1);

INSERT INTO STOCK_PRODUCTO(PRODUCTO_ID, TALLE, CANTIDAD) VALUES
    (1, 40, 3), ---ADIDAS JUMPCRAZY
    (1, 42, 10), ---ADIDAS JUMPCRAZY
    (1, 37, 1), ---ADIDAS JUMPCRAZY
    (2, 30, 2), ---VANS CLASSICS
    (3, 46, 5), ---DC BIG SKATER
    (4, 41, 8), -- NIKE AIR MAX
    (4, 43, 5), -- NIKE AIR MAX
    (5, 38, 12), -- CONVERSE ALL STAR
    (5, 40, 6), -- CONVERSE ALL STAR
    (6, 39, 15), -- REEBOK CLASSIC
    (6, 44, 7), -- REEBOK CLASSIC
    (7, 42, 9), -- PUMA SUEDE
    (7, 44, 4); -- PUMA SUEDE

INSERT INTO GRUPO_CATEGORIA(ID, NOMBRE) VALUES (1, 'Marca');
INSERT INTO GRUPO_CATEGORIA(ID, NOMBRE) VALUES (2, 'Segmento');
INSERT INTO GRUPO_CATEGORIA(ID, NOMBRE) VALUES (3, 'Deporte');
INSERT INTO GRUPO_CATEGORIA(ID, NOMBRE) VALUES (4, 'Estilo');

INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (1, 1, 'Adidas');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (1, 2, 'Vans');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (1, 3, 'DC');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (2, 4, 'Hombre');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (2, 5, 'Mujer');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (2, 6, 'Niño');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (2, 7, 'Niña');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (3, 8, 'Running');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (3, 9, 'Skateboarding');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (4, 10, 'Casual');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (4, 11, 'Elegante');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (1, 12, 'Converse');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (1, 13, 'Reebok');
INSERT INTO CATEGORIA(GRUPO_ID, ID, NOMBRE) VALUES (1, 14, 'Puma');


INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (1, 1);
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (1, 4);
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (2, 2);
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (2, 4);
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (3, 3);
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (3, 5);
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (4, 1); -- NIKE AIR MAX -> Nike (Marca)
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (4, 8); -- NIKE AIR MAX -> Running (Deporte)
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (5, 12); -- CONVERSE ALL STAR -> Converse (Marca)
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (5, 10); -- CONVERSE ALL STAR -> Casual (Estilo)
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (6, 13); -- REEBOK CLASSIC -> DC (Marca)
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (6, 9); -- REEBOK CLASSIC -> Skateboarding (Deporte)
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (7, 14); -- PUMA SUEDE -> DC (Marca)
INSERT INTO PRODUCTO_CATEGORIA(PRODUCTO_ID, CATEGORIA_ID) VALUES (7, 11); -- PUMA SUEDE -> Elegante (Estilo)
